
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS "Eukami_v1";

ALTER SCHEMA "Eukami_v1" OWNER TO "postgres";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE SCHEMA IF NOT EXISTS "supabase_migrations";

ALTER SCHEMA "supabase_migrations" OWNER TO "postgres";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."fulfillmentTypes" AS ENUM (
    'OPEN',
    'IN_PROGRESS',
    'ON_HOLD',
    'FULFILLED',
    'UNFULFILLED'
);

ALTER TYPE "public"."fulfillmentTypes" OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Admin_User" (
    "staff_ID" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "firstName" character varying NOT NULL,
    "surname" character varying NOT NULL,
    "email" character varying NOT NULL,
    "address" character varying NOT NULL
);

ALTER TABLE "Eukami_v1"."Admin_User" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Bank_account" (
    "customer_ID" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "sort_code" character varying NOT NULL,
    "account_number" character varying NOT NULL
);

ALTER TABLE "Eukami_v1"."Bank_account" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Cart" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "customer_id" bigint,
    "checkoutUrl" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "total" double precision DEFAULT '0'::double precision,
    "totalQuantity" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "Eukami_v1"."Cart" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "Eukami_v1"."CartLineItem" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "product_variant" bigint,
    "quantity" smallint NOT NULL,
    "cart_id" bigint NOT NULL
);

ALTER TABLE "Eukami_v1"."CartLineItem" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."CartLineItem" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."CartLineItem_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "Eukami_v1"."Cart" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."Cart_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Checkout" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "completed_at" timestamp with time zone,
    "email" "text",
    "order_id" bigint
);

ALTER TABLE "Eukami_v1"."Checkout" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."Checkout" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."Checkout_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Collection" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "images" "json",
    "description" character varying,
    "name" "text" DEFAULT ''::"text",
    "isFeatured" boolean DEFAULT false NOT NULL
);

ALTER TABLE "Eukami_v1"."Collection" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."Collection" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."Collections_collection_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Customer" (
    "Customer_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "firstName" character varying NOT NULL,
    "lastName" character varying NOT NULL,
    "email" character varying NOT NULL,
    "address" character varying NOT NULL
);

ALTER TABLE "Eukami_v1"."Customer" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."Customer" ALTER COLUMN "Customer_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."Customer_Customer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "Eukami_v1"."LineItem" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "product_variant" bigint,
    "quantity" smallint NOT NULL
);

ALTER TABLE "Eukami_v1"."LineItem" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."LineItem" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."LineItem_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Order" (
    "customer" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "product" bigint NOT NULL,
    "billing_address" character varying NOT NULL,
    "id" bigint NOT NULL,
    "fulfillmentStatus" "public"."fulfillmentTypes" DEFAULT 'OPEN'::"public"."fulfillmentTypes" NOT NULL
);

ALTER TABLE "Eukami_v1"."Order" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."Order" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."Order_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Product" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "description" "text" DEFAULT ''::"text",
    "price" double precision DEFAULT '0'::double precision NOT NULL,
    "collection_id" bigint,
    "availableForSale" boolean DEFAULT true NOT NULL,
    "salePrice" double precision,
    "sku" character varying,
    "images" "json",
    "inventory" bigint DEFAULT '0'::bigint NOT NULL,
    "isFeatured" boolean DEFAULT false NOT NULL,
    "features" "text" DEFAULT ''::"text"
);

ALTER TABLE "Eukami_v1"."Product" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "Eukami_v1"."ProductVariant" (
    "product_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "description" "text" DEFAULT ''::"text",
    "price" double precision DEFAULT '0'::double precision NOT NULL,
    "availableForSale" boolean DEFAULT true NOT NULL,
    "salePrice" double precision,
    "sku" character varying,
    "images" "json",
    "inventory" bigint DEFAULT '0'::bigint NOT NULL,
    "isFeatured" boolean DEFAULT false NOT NULL,
    "features" "text" DEFAULT ''::"text",
    "id" bigint NOT NULL
);

ALTER TABLE "Eukami_v1"."ProductVariant" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."ProductVariant" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."ProductVariant_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Product_Image" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "image_url" "json",
    "product_id" bigint NOT NULL
);

ALTER TABLE "Eukami_v1"."Product_Image" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."Product_Image" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."Product_Image_image_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Product_Modification" (
    "staff_ID" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "product_ID" bigint NOT NULL
);

ALTER TABLE "Eukami_v1"."Product_Modification" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."Product" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."Product_Product_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Review" (
    "customer_ID" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "product_ID" bigint NOT NULL,
    "rating" bigint NOT NULL
);

ALTER TABLE "Eukami_v1"."Review" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Saved_Item" (
    "customer_ID" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "product_ID" bigint NOT NULL
);

ALTER TABLE "Eukami_v1"."Saved_Item" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Setting" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "setting_key" "text" NOT NULL,
    "setting_value" "jsonb",
    "setting_meta" "jsonb"
);

ALTER TABLE "Eukami_v1"."Setting" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."Setting" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."Setting_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "Eukami_v1"."Admin_User" ALTER COLUMN "staff_ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."Staff_staff_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "Eukami_v1"."Support_Ticket" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "email" "text",
    "phone" "text",
    "message" "text",
    "customer_id" bigint
);

ALTER TABLE "Eukami_v1"."Support_Ticket" OWNER TO "postgres";

ALTER TABLE "Eukami_v1"."Support_Ticket" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Eukami_v1"."Support_Ticket_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."collections" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" "text" DEFAULT ''::"text" NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "image" "json",
    "slug" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "products" bigint
);

ALTER TABLE "public"."collections" OWNER TO "postgres";

ALTER TABLE "public"."collections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."collections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."customer" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "amountSpent" real DEFAULT '0'::real NOT NULL,
    "displayName" "text" NOT NULL,
    "email" "text",
    "firstName" "text",
    "lastName" "text",
    "numberOfOrders" integer DEFAULT 0 NOT NULL,
    "shippingAddress" "text",
    "billingAddress" "text",
    "orders" bigint
);

ALTER TABLE "public"."customer" OWNER TO "postgres";

ALTER TABLE "public"."customer" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."customer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."orders" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "billingAddress" "text" NOT NULL,
    "canceledAt" timestamp with time zone,
    "totalPrice" real NOT NULL,
    "customerUrl" "text",
    "email" "text" NOT NULL,
    "financialStatus" "text",
    "fulfillmentStatus" "text" DEFAULT '"OPEN"'::"text" NOT NULL,
    "shippingAddress" "text" NOT NULL,
    "statusUrl" "text" DEFAULT ''::"text" NOT NULL,
    "lineItems" bigint[]
);

ALTER TABLE "public"."orders" OWNER TO "postgres";

ALTER TABLE "public"."orders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."orders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "description" "text" DEFAULT ''::"text",
    "tags" "json" DEFAULT '[]'::"json",
    "sku" "text",
    "weight" real,
    "collections" bigint,
    "availableForSale" boolean DEFAULT true NOT NULL,
    "price" real DEFAULT '0'::real NOT NULL,
    "salePrice" real,
    "images" "json"
);

ALTER TABLE "public"."products" OWNER TO "postgres";

ALTER TABLE "public"."products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "updated_at" timestamp with time zone,
    "username" "text",
    "full_name" "text",
    "avatar_url" "text",
    "website" "text",
    CONSTRAINT "username_length" CHECK (("char_length"("username") >= 3))
);

ALTER TABLE "public"."profiles" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "supabase_migrations"."schema_migrations" (
    "version" "text" NOT NULL,
    "statements" "text"[],
    "name" "text"
);

ALTER TABLE "supabase_migrations"."schema_migrations" OWNER TO "postgres";

ALTER TABLE ONLY "Eukami_v1"."Bank_account"
    ADD CONSTRAINT "Bank_account_account_number_key" UNIQUE ("account_number");

ALTER TABLE ONLY "Eukami_v1"."Bank_account"
    ADD CONSTRAINT "Bank_account_customer_ID_key" UNIQUE ("customer_ID");

ALTER TABLE ONLY "Eukami_v1"."Bank_account"
    ADD CONSTRAINT "Bank_account_pkey" PRIMARY KEY ("customer_ID", "sort_code");

ALTER TABLE ONLY "Eukami_v1"."Bank_account"
    ADD CONSTRAINT "Bank_account_sort_code_key" UNIQUE ("sort_code");

ALTER TABLE ONLY "Eukami_v1"."CartLineItem"
    ADD CONSTRAINT "CartLineItem_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "Eukami_v1"."Cart"
    ADD CONSTRAINT "Cart_checkoutUrl_key" UNIQUE ("checkoutUrl");

ALTER TABLE ONLY "Eukami_v1"."Cart"
    ADD CONSTRAINT "Cart_customer_id_key" UNIQUE ("customer_id");

ALTER TABLE ONLY "Eukami_v1"."Cart"
    ADD CONSTRAINT "Cart_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "Eukami_v1"."Checkout"
    ADD CONSTRAINT "Checkout_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "Eukami_v1"."Collection"
    ADD CONSTRAINT "Collections_collection_ID_key" UNIQUE ("id");

ALTER TABLE ONLY "Eukami_v1"."Collection"
    ADD CONSTRAINT "Collections_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "Eukami_v1"."Customer"
    ADD CONSTRAINT "Customer_email_key" UNIQUE ("email");

ALTER TABLE ONLY "Eukami_v1"."Customer"
    ADD CONSTRAINT "Customer_pkey" PRIMARY KEY ("Customer_id");

ALTER TABLE ONLY "Eukami_v1"."LineItem"
    ADD CONSTRAINT "LineItem_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "Eukami_v1"."Order"
    ADD CONSTRAINT "Order_id_key" UNIQUE ("id");

ALTER TABLE ONLY "Eukami_v1"."Order"
    ADD CONSTRAINT "Order_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "Eukami_v1"."Order"
    ADD CONSTRAINT "Orders_customer_ID_key" UNIQUE ("customer");

ALTER TABLE ONLY "Eukami_v1"."Order"
    ADD CONSTRAINT "Orders_product_ID_key" UNIQUE ("product");

ALTER TABLE ONLY "Eukami_v1"."ProductVariant"
    ADD CONSTRAINT "ProductVariant_id_key" UNIQUE ("id");

ALTER TABLE ONLY "Eukami_v1"."ProductVariant"
    ADD CONSTRAINT "ProductVariant_pkey" PRIMARY KEY ("product_id");

ALTER TABLE ONLY "Eukami_v1"."Product_Image"
    ADD CONSTRAINT "Product_Image_Product_ID_key" UNIQUE ("product_id");

ALTER TABLE ONLY "Eukami_v1"."Product_Image"
    ADD CONSTRAINT "Product_Image_image_ID_key" UNIQUE ("id");

ALTER TABLE ONLY "Eukami_v1"."Product_Image"
    ADD CONSTRAINT "Product_Image_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "Eukami_v1"."Product_Modification"
    ADD CONSTRAINT "Product_Modification_pkey" PRIMARY KEY ("staff_ID", "product_ID");

ALTER TABLE ONLY "Eukami_v1"."Product_Modification"
    ADD CONSTRAINT "Product_Modification_product_ID_key" UNIQUE ("product_ID");

ALTER TABLE ONLY "Eukami_v1"."Product_Modification"
    ADD CONSTRAINT "Product_Modification_staff_ID_key" UNIQUE ("staff_ID");

ALTER TABLE ONLY "Eukami_v1"."Product"
    ADD CONSTRAINT "Product_Product_ID_key" UNIQUE ("id");

ALTER TABLE ONLY "Eukami_v1"."Product"
    ADD CONSTRAINT "Product_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "Eukami_v1"."Review"
    ADD CONSTRAINT "Reviews_customer_ID_key" UNIQUE ("customer_ID");

ALTER TABLE ONLY "Eukami_v1"."Review"
    ADD CONSTRAINT "Reviews_pkey" PRIMARY KEY ("customer_ID", "product_ID");

ALTER TABLE ONLY "Eukami_v1"."Review"
    ADD CONSTRAINT "Reviews_product_ID_key" UNIQUE ("product_ID");

ALTER TABLE ONLY "Eukami_v1"."Saved_Item"
    ADD CONSTRAINT "Saved_Items_customer_ID_key" UNIQUE ("customer_ID");

ALTER TABLE ONLY "Eukami_v1"."Saved_Item"
    ADD CONSTRAINT "Saved_Items_pkey" PRIMARY KEY ("customer_ID", "product_ID");

ALTER TABLE ONLY "Eukami_v1"."Saved_Item"
    ADD CONSTRAINT "Saved_Items_product_ID_key" UNIQUE ("product_ID");

ALTER TABLE ONLY "Eukami_v1"."Setting"
    ADD CONSTRAINT "Setting_pkey" PRIMARY KEY ("id", "setting_key");

ALTER TABLE ONLY "Eukami_v1"."Admin_User"
    ADD CONSTRAINT "Staff_email_key" UNIQUE ("email");

ALTER TABLE ONLY "Eukami_v1"."Admin_User"
    ADD CONSTRAINT "Staff_pkey" PRIMARY KEY ("staff_ID");

ALTER TABLE ONLY "Eukami_v1"."Admin_User"
    ADD CONSTRAINT "Staff_staff_ID_key" UNIQUE ("staff_ID");

ALTER TABLE ONLY "Eukami_v1"."Support_Ticket"
    ADD CONSTRAINT "Support_Ticket_id_key" UNIQUE ("id");

ALTER TABLE ONLY "Eukami_v1"."Support_Ticket"
    ADD CONSTRAINT "Support_Ticket_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."collections"
    ADD CONSTRAINT "collections_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."customer"
    ADD CONSTRAINT "customer_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");

ALTER TABLE ONLY "supabase_migrations"."schema_migrations"
    ADD CONSTRAINT "schema_migrations_pkey" PRIMARY KEY ("version");

ALTER TABLE ONLY "Eukami_v1"."Bank_account"
    ADD CONSTRAINT "Eukami_v1_Bank_account_customer_ID_fkey" FOREIGN KEY ("customer_ID") REFERENCES "Eukami_v1"."Customer"("Customer_id");

ALTER TABLE ONLY "Eukami_v1"."CartLineItem"
    ADD CONSTRAINT "Eukami_v1_CartLineItem_cart_id_fkey" FOREIGN KEY ("cart_id") REFERENCES "Eukami_v1"."Cart"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "Eukami_v1"."Checkout"
    ADD CONSTRAINT "Eukami_v1_Checkout_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "Eukami_v1"."Order"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "Eukami_v1"."Order"
    ADD CONSTRAINT "Eukami_v1_Orders_customer_ID_fkey" FOREIGN KEY ("customer") REFERENCES "Eukami_v1"."Customer"("Customer_id");

ALTER TABLE ONLY "Eukami_v1"."Order"
    ADD CONSTRAINT "Eukami_v1_Orders_product_ID_fkey" FOREIGN KEY ("product") REFERENCES "Eukami_v1"."Product"("id");

ALTER TABLE ONLY "Eukami_v1"."ProductVariant"
    ADD CONSTRAINT "Eukami_v1_ProductVariant_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "Eukami_v1"."Product"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "Eukami_v1"."Product_Image"
    ADD CONSTRAINT "Eukami_v1_Product_Image_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "Eukami_v1"."Product"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "Eukami_v1"."Product_Modification"
    ADD CONSTRAINT "Eukami_v1_Product_Modification_product_ID_fkey" FOREIGN KEY ("product_ID") REFERENCES "Eukami_v1"."Product"("id");

ALTER TABLE ONLY "Eukami_v1"."Product_Modification"
    ADD CONSTRAINT "Eukami_v1_Product_Modification_staff_ID_fkey" FOREIGN KEY ("staff_ID") REFERENCES "Eukami_v1"."Admin_User"("staff_ID");

ALTER TABLE ONLY "Eukami_v1"."Product"
    ADD CONSTRAINT "Eukami_v1_Product_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "Eukami_v1"."Collection"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "Eukami_v1"."Review"
    ADD CONSTRAINT "Eukami_v1_Reviews_customer_ID_fkey" FOREIGN KEY ("customer_ID") REFERENCES "Eukami_v1"."Customer"("Customer_id");

ALTER TABLE ONLY "Eukami_v1"."Review"
    ADD CONSTRAINT "Eukami_v1_Reviews_product_ID_fkey" FOREIGN KEY ("product_ID") REFERENCES "Eukami_v1"."Product"("id");

ALTER TABLE ONLY "Eukami_v1"."Saved_Item"
    ADD CONSTRAINT "Eukami_v1_Saved_Items_customer_ID_fkey" FOREIGN KEY ("customer_ID") REFERENCES "Eukami_v1"."Customer"("Customer_id");

ALTER TABLE ONLY "Eukami_v1"."Saved_Item"
    ADD CONSTRAINT "Eukami_v1_Saved_Items_product_ID_fkey" FOREIGN KEY ("product_ID") REFERENCES "Eukami_v1"."Product"("id");

ALTER TABLE ONLY "Eukami_v1"."Support_Ticket"
    ADD CONSTRAINT "Eukami_v1_Support_Ticket_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "Eukami_v1"."Customer"("Customer_id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."collections"
    ADD CONSTRAINT "collections_products_fkey" FOREIGN KEY ("products") REFERENCES "public"."products"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."customer"
    ADD CONSTRAINT "customer_orders_fkey" FOREIGN KEY ("orders") REFERENCES "public"."orders"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_collections_fkey" FOREIGN KEY ("collections") REFERENCES "public"."collections"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE "Eukami_v1"."Admin_User" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Bank_account" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Cart" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."CartLineItem" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Checkout" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Collection" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Customer" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable All for authenticated users only" ON "Eukami_v1"."Product" TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable access for all users" ON "Eukami_v1"."Cart" USING (true) WITH CHECK (true);

CREATE POLICY "Enable access for all users" ON "Eukami_v1"."CartLineItem" USING (true) WITH CHECK (true);

CREATE POLICY "Enable access for all users" ON "Eukami_v1"."Checkout" USING (true) WITH CHECK (true);

CREATE POLICY "Enable access for all users" ON "Eukami_v1"."LineItem" USING (true) WITH CHECK (true);

CREATE POLICY "Enable access for all users" ON "Eukami_v1"."ProductVariant" USING (true) WITH CHECK (true);

CREATE POLICY "Enable all access for all users" ON "Eukami_v1"."Product" USING (true) WITH CHECK (true);

CREATE POLICY "Enable all access for all users" ON "Eukami_v1"."Support_Ticket" USING (true) WITH CHECK (true);

CREATE POLICY "Enable all access to all" ON "Eukami_v1"."Collection" USING (true) WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "Eukami_v1"."Collection" TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "Eukami_v1"."Customer" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "Eukami_v1"."Order" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "Eukami_v1"."Product" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "Eukami_v1"."Product_Image" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "Eukami_v1"."Admin_User" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "Eukami_v1"."Bank_account" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "Eukami_v1"."Collection" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "Eukami_v1"."Customer" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "Eukami_v1"."Product" FOR SELECT TO "authenticated", "anon", "service_role" USING (true);

CREATE POLICY "Enable read access for all users" ON "Eukami_v1"."Product_Image" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "Eukami_v1"."Product_Modification" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "Eukami_v1"."Review" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "Eukami_v1"."Saved_Item" FOR SELECT USING (true);

ALTER TABLE "Eukami_v1"."LineItem" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Order" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Product" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."ProductVariant" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Product_Image" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Product_Modification" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Review" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Saved_Item" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Setting" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "Eukami_v1"."Support_Ticket" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));

CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));

ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "Eukami_v1" TO "anon";
GRANT USAGE ON SCHEMA "Eukami_v1" TO "authenticated";
GRANT USAGE ON SCHEMA "Eukami_v1" TO "service_role";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Admin_User" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Admin_User" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Admin_User" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Bank_account" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Bank_account" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Bank_account" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Cart" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Cart" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Cart" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."CartLineItem" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."CartLineItem" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."CartLineItem" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."CartLineItem_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."CartLineItem_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."CartLineItem_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."Cart_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."Cart_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."Cart_id_seq" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Checkout" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Checkout" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Checkout" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."Checkout_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."Checkout_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."Checkout_id_seq" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Collection" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Collection" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Collection" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."Collections_collection_ID_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."Collections_collection_ID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."Collections_collection_ID_seq" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Customer" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Customer" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Customer" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."Customer_Customer_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."Customer_Customer_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."Customer_Customer_id_seq" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."LineItem" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."LineItem" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."LineItem" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."LineItem_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."LineItem_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."LineItem_id_seq" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Order" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Order" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Order" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."Order_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."Order_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."Order_id_seq" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Product" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Product" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Product" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."ProductVariant" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."ProductVariant" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."ProductVariant" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."ProductVariant_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."ProductVariant_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."ProductVariant_id_seq" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Product_Image" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Product_Image" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Product_Image" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."Product_Image_image_ID_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."Product_Image_image_ID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."Product_Image_image_ID_seq" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Product_Modification" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Product_Modification" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Product_Modification" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."Product_Product_ID_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."Product_Product_ID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."Product_Product_ID_seq" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Review" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Review" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Review" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Saved_Item" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Saved_Item" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Saved_Item" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Setting" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Setting" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Setting" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."Setting_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."Setting_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."Setting_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."Staff_staff_ID_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."Staff_staff_ID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."Staff_staff_ID_seq" TO "service_role";

GRANT ALL ON TABLE "Eukami_v1"."Support_Ticket" TO "anon";
GRANT ALL ON TABLE "Eukami_v1"."Support_Ticket" TO "authenticated";
GRANT ALL ON TABLE "Eukami_v1"."Support_Ticket" TO "service_role";

GRANT ALL ON SEQUENCE "Eukami_v1"."Support_Ticket_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "Eukami_v1"."Support_Ticket_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "Eukami_v1"."Support_Ticket_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."collections" TO "anon";
GRANT ALL ON TABLE "public"."collections" TO "authenticated";
GRANT ALL ON TABLE "public"."collections" TO "service_role";

GRANT ALL ON SEQUENCE "public"."collections_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."collections_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."collections_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."customer" TO "anon";
GRANT ALL ON TABLE "public"."customer" TO "authenticated";
GRANT ALL ON TABLE "public"."customer" TO "service_role";

GRANT ALL ON SEQUENCE "public"."customer_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."customer_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."customer_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."orders" TO "anon";
GRANT ALL ON TABLE "public"."orders" TO "authenticated";
GRANT ALL ON TABLE "public"."orders" TO "service_role";

GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";

GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "Eukami_v1" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "Eukami_v1" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "Eukami_v1" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "Eukami_v1" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "Eukami_v1" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "Eukami_v1" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "Eukami_v1" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "Eukami_v1" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "Eukami_v1" GRANT ALL ON TABLES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
